CREATE TABLE case_decision (
_id int DEFAULT NULL,
CASE_ID int DEFAULT NULL,
SENTENCE text,
PARAGRAPH text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE case_info (
CASE_ID int NOT NULL AUTO_INCREMENT,
CASE_NAME varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
CASE_KIND varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
INCIDENT_REASON text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
COURT_NAME varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
INDEX_NO varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
SLIPOP_NO varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
JUDGE_NAME varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
PLAINTIFF_NAME varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
DEFENDANT_NAME varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
DECISION_DATE date NOT NULL,
PLAINTIFF_LAWYER_NUM int NOT NULL,
DEFENDANT_LAWYER_NUM int NOT NULL,
SUMMARY text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
RESULT varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
PRIMARY KEY (CASE_ID),
KEY idx_decision_date (DECISION_DATE)
) ENGINE=InnoDB AUTO_INCREMENT=108004 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_090;

CREATE TABLE `defendant_lawyer` (
  `_id` int NOT NULL AUTO_INCREMENT,
  `CASE_ID` int NOT NULL,
  `LAWYER_NO` int NOT NULL,
  `LAWYER_NAME` varchar(1024) NOT NULL,
  `CLIENT_NAME` varchar(1024) NOT NULL,
  `RESULT` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `CASE_ID` (`CASE_ID`),
  KEY `LAWYER_NO` (`LAWYER_NO`),
  CONSTRAINT `defendant_lawyer_ibfk_1` FOREIGN KEY (`CASE_ID`) REFERENCES `case_info` (`CASE_ID`) ON UPDATE CASCADE,
  CONSTRAINT `defendant_lawyer_ibfk_2` FOREIGN KEY (`LAWYER_NO`) REFERENCES `lawyer_info` (`_id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=264948 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `lawyer_info` (
  `_id` int NOT NULL AUTO_INCREMENT,
  `LAWYER_NAME` varchar(256) NOT NULL,
  `LAWFIRM` varchar(1024) DEFAULT NULL,
  `COUNT` int DEFAULT NULL,
  `WIN` int DEFAULT NULL,
  `LOSE` int DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB AUTO_INCREMENT=226802 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `plaintiff_lawyer` (
  `_id` int NOT NULL AUTO_INCREMENT,
  `CASE_ID` int NOT NULL,
  `LAWYER_NO` int NOT NULL,
  `LAWYER_NAME` varchar(1024) NOT NULL,
  `CLIENT_NAME` varchar(1024) NOT NULL,
  `RESULT` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `CASE_ID` (`CASE_ID`),
  KEY `LAWYER_NO` (`LAWYER_NO`),
  CONSTRAINT `plaintiff_lawyer_ibfk_1` FOREIGN KEY (`CASE_ID`) REFERENCES `case_info` (`CASE_ID`) ON UPDATE CASCADE,
  CONSTRAINT `plaintiff_lawyer_ibfk_2` FOREIGN KEY (`LAWYER_NO`) REFERENCES `lawyer_info` (`_id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=97988 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `user` (
  `_id` int NOT NULL AUTO_INCREMENT,
  `email` varchar(256) NOT NULL,
  `password` varchar(256) NOT NULL,
  `role` varchar(256) NOT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;