import re

# reulst 키워드
KEYWORDS = [
    "liability", "damage", "verdict", "duty", "pay", "guilty", "injunction","conviction", "sentence", "plea bargain", 
    "contract","performance", "remedy","order","causation", "fail", "evidence", "release",
    "enrichment", "material", "harm", "judgement", "liable", "dismiss", "action", "grant","denied", "deny", 
    "prove", "acquittal","exoneration", "doubt", "mistrial", "breach", "claim" "entitle", "lack", "proof",
    "negligence", "limitation", "risk", "de minimis", "faith", "lack", "standing", "mitigation", "waiver", 
]   

# 변호사 검색용 키워드
ATTORNEY_KEYWORD = ["petitioner", "plaintiff", "respondent", "defendant"] 

# 변호인 키워드
BEFORE_ATTORNEY_COMPILE = [
    "Plaintiff\'?\w?\s?*\.",
    "Petitioner\'?\w?\s?*\.",
    "Defendant\'?\w?\s?*\.",
    "Respondent\'?\w?\s?*\."
] 

AFTER_ATTORNEY_COMPILE = [
    "Plaintiff'?\w?",
    "Petitioner'?\w?",
    "Defendant'?\w?",
    "Respondent'?\w?"
]

# 제거 키워드
REMOVE_KEYWORD = ["we", ",", "Esq", "Esq.", "ESQ", "ESQ." "", "", "P.C.", " .", "Plaintiff", "Petitioner", "Defendant", "Respondent", "Appellant" "appellant", "respondent", "plaintiff", "petitional", "defendent"]

LOC = [
    "New York",
    "N.Y.",
    "NY",
    "Brooklyn"
]

LAW_FIRMS = [
    "Pollack Pollack Isaac & Decicco",
    "Fabiani Cohen & Hall LLP",
    "Nicoletti Hornig & Sweeney",
    "Bartholow & Miller",
    "Akiva Shapiro Firm",
    "Ainsworth Gorkin PLLC",
    "Cramer & Summit",
    "Lieb at Law",
    "Hegge & Confusione",
    "Lipsig, Shapey, Manus & Moverman, P.C.",
    "Gannon, Rosenfarb & Drossman",
    "AWN&R Commercial Law Group",
    "Central Islip",
    "Woods Oviatt Gilman LLP",
    "Skadden, Arps, Slate, Meagher & Flom LLP",
    "Latham & Watkins LLP",
    "Baker McKenzie",
    "Sidley Austin LLP",
    "Hogan Lovells",
    "Clifford Chance LLP",
    "White & Case LLP",
    "Jones Day",
    "Kirkland & Ellis LLP",
    "Simpson Thacher & Bartlett LLP",
    "Davis Polk & Wardwell LLP",
    "Paul, Weiss, Rifkind, Wharton & Garrison LLP",
    "Morgan, Lewis & Bockius LLP",
    "Mayer Brown LLP",
    "Cleary Gottlieb Steen & Hamilton LLP",
    "Ropes & Gray LLP",
    "WilmerHale",
    "Weil, Gotshal & Manges LLP",
    "Arnold & Porter",
    "Shearman & Sterling LLP",
    "Dechert LLP",
    "O'Melveny & Myers LLP",
    "Freshfields Bruckhaus Deringer LLP",
    "Reed Smith LLP",
    "Gibson, Dunn & Crutcher LLP",
    "Proskauer Rose LLP",
    "Baker Botts LLP",
    "Hunton Andrews Kurth LLP",
    "Akin Gump Strauss Hauer & Feld LLP",
    "Quinn Emanuel Urquhart & Sullivan LLP",
    "Covington & Burling LLP",
    "Greenberg Traurig, LLP",
    "Sullivan & Cromwell LLP",
    "Dentons",
    "Perkins Coie LLP",
    "Ballard Spahr LLP",
    "McDermott Will & Emery LLP",
    "Winston & Strawn LLP",
    "Paul Hastings LLP",
    "Steptoe & Johnson LLP",
    "Nelson Mullins Riley & Scarborough LLP",
    "Morrison & Foerster LLP",
    "Vinson & Elkins LLP",
    "Husch Blackwell LLP",
    "Holland & Knight LLP",
    "Seyfarth Shaw LLP",
    "Lewis Brisbois Bisgaard & Smith LLP",
    "Schulte Roth & Zabel LLP",
    "Foley & Lardner LLP",
    "Orrick, Herrington & Sutcliffe LLP",
    "DLA Piper",
    "Eversheds Sutherland",
    "Bryan Cave Leighton Paisner LLP",
    "K&L Gates LLP",
    "Blank Rome LLP",
    "Alston & Bird LLP",
    "Davis Wright Tremaine LLP",
    "McGuireWoods LLP",
    "Jackson Lewis P.C.",
    "Squire Patton Boggs LLP",
    "Littler Mendelson P.C.",
    "Mintz Levin Cohn Ferris Glovsky and Popeo P.C.",
    "Arnold & Porter Kaye Scholer LLP",
    "Zuckerman Spaeder LLP",
    "Richards, Layton & Finger, P.A.",
    "Bingham Greenebaum Doll LLP",
    "Hogan Lovells",
    "Dorsey & Whitney LLP",
    "Akerman LLP",
    "Carlton Fields",
    "Williams & Connolly LLP",
    "Kramer Levin Naftalis & Frankel LLP",
    "Day Pitney LLP",
    "Stradley Ronon Stevens & Young LLP",
    "Munger, Tolles & Olson LLP",
    "Venable LLP",
    "Wilmer Cutler Pickering Hale and Dorr LLP",
    "Kilpatrick Townsend & Stockton LLP",
    "Coblentz Patch Duffy & Bass LLP",
    "Farella Braun + Martel LLP",
    "Cooley LLP",
    "Morgan Lewis & Bockius LLP",
    "Riker Danzig Scherer Hyland & Perretti LLP",
    "Stinson LLP",
    "Gardere Wynne Sewell LLP",
    "Schwabe, Williamson & Wyatt",
    "Barnes & Thornburg LLP",
    "Quarles & Brady LLP",
    "Madsen, Goldman & Holm LLP",
    "Davis Polk & Wardwell LLP",
    "Crowell & Moring LLP",
    "Pillsbury Winthrop Shaw Pittman LLP",
    "McCarter & English LLP",
    "Lewis Brisbois",
    "Foley & Lardner LLP",
    "Stradley Ronon Stevens & Young LLP",
    "Lowenstein Sandler LLP",
]